### ISSUE TITLE
helm operate chart needs to support migration

### ISSUE THREAD

**Issue by xuanzhong** [zeebe-io/zeebe-operate-helm#12]
It requires an init container as documented here:
https://docs.zeebe.io/operate-deployment-guide/schema-and-migration.html#example-for-migrate-in-kubernetes

**Comment by salaboy** [comment]
@xuanzhong thanks for reporting this.. can you help us out by sending a PR maybe to https://github.com/zeebe-io/zeebe-helm-profiles with an example.. yaml file with that extension

**Comment by xuanzhong** [comment]
@salaboy I can not get the init container working. It is hard coded to use localhost:9200 for the elasticsearch cluster.

**Comment by oceyral** [comment]
Hi,

Is this still required ? Documentation states that Operate will, by default, automatically do the migration on startup, but then gives the initContainer example, so it is a bit confusing. 

I imagine at a minimum we need to set strategy type to `recreate` on the pod template in the deployment, to avoid having two Operate versions running at the same time, but beyond that I'm a bit confused on whether we still need the initContainer or not.

**Comment by ChrisKujawa** [comment]
I feel this is out date if not feel free to open it again in the mono repo https://github.com/camunda-community-hub/camunda-cloud-helm
