### ISSUE TITLE
Way to disable auth completely?

### ISSUE THREAD

**Issue by CodechCFA** [zeebe-io/zeebe-operate-helm#13]
We have put operate behind an auth proxy that uses OIDC, therefore we have no use for the internal operate auth. Is there any way we can disable it?

**Comment by salaboy** [comment]
Hi @CodechCFA i will check with the Operate team, I am not sure if that can be done now, @sdorokhova can you share some details about that?

**Comment by sdorokhova** [comment]
Hi, @CodechCFA , no, unfortunately it's not possible currently in Operate to disable authentication.

**Comment by CodechCFA** [comment]
@sdorokhova gotcha and there's no way to use Okta for auth, only Auth0 right?

**Comment by sdorokhova** [comment]
Exactly. Currently we support only Auth0 for Single Sign-on case.
